export { default as addIcon } from './add.svg';
export { default as visibilityIcon } from './visibility.svg';
export { default as visibilityOffIcon } from './visibility_off.svg';
export { default as homeIcon } from './home.svg';
export { default as bookmarkIcon} from './bookmark.svg';
export { default as personIcon } from './person.svg';
export { default as menuIcon } from './more_vert.svg';
export { default as playIcon } from './play_arrow.svg';
export { default as searchIcon } from './search.svg';
export { default as logoutIcon } from './logout.svg';
export { default as uploadIcon } from './upload.svg'; 
